def jekyll(opts="", path="")
  sh "rm -rf _site"
  sh path + "jekyll " + opts
end

desc "Build site using Jekyll"
task :build do
  jekyll "--pygments"
end

desc "Serve on Localhost with port 4000"
task :default do
  jekyll "--server --pygments --auto"
end

desc "Deploy to Dev"
task :deploy => :"deploy:dev"

desc "Publish"
task :publish => :"deploy:all"

namespace :deploy do
  desc "Deploy to github"
  task :dev => :build do
    push "github"
  end
  
  desc "Deploy to Live"
  task :live => :build do
    push "origin"
  end
  
  desc "Deploy to Dev and Live"
  task :all => [:dev, :live]
  
  def push(repo)
    sh "git add ."
    sh "git commit -m 'updated via rake...'"
    sh "git push #{repo} master"
  end
end